name: "Security CI/CD"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-22.04
    container: python:2.7-buster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade "pip<21" "setuptools<45" "wheel<0.38"
          pip install --use-deprecated=legacy-resolver -r requirements.txt

      - name: Run Django tests
        run: |
          coverage run manage.py test app
          coverage report

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{ matrix.language }}'
